---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf2gAwIBAgIQYFASNyN+9WqZI5ApLWK07zAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yNDExMTUwOTA4MDBaFw0zNDExMTMwOTA4
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAEwABlU0nUYOEKfkIXsC37UtmUU8sTQTexnuYW8Of4OxaoqxvM7lAVD+4z
          yMRmz4wA6Q2S3H9XeKm5bVtly5K09KNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCDPa8BpVFr3wxwqEjz0jBqxMQvzO0meazucYwIEIcPLmDAKBggqhkjOPQQD
          AgNIADBFAiAr6VvUt5PkLWEcOEZVFbX5zIzL9Akha+evz++hGj/wLAIhAPSBJBRw
          VJbPoAP/8oMCSVmn6UAUrIb75NUbYSWSBlNr
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQCNX1eELNrFIcBIGn1NiPVDAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMS5leGFtcGxlLmNvbTAeFw0yNDExMTUwOTA4MDBaFw0zNDExMTMwOTA4MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          kOrBbqFlCG1cKGMPaH27Sy9Fyvrs6s+Ju6iFamkvfMoUQN4MQisYjxLzc8HnydLn
          mcNDQgvEVjo5aEY8nqRq3qNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAc
          UR0tq1/kQIBPfcXpcg8bQsRWxyxCtP4MuF8h02okhDAKBggqhkjOPQQDAgNIADBF
          AiA7Uk6MW9wLT/BRtI+sGipgsiLJpvCs7Chyjla2bgPNYAIhAMrBo4qYlGzxVQVa
          m2DNnAsa/CvvbVHz+3TFwRa9xvRr
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
