---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAPy3jfJFLBbpxff84pGerMYwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjQxMTE1MDkwODAwWhcNMzQxMTEzMDkw
          ODAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABCPUI9LgrvfXRf6FvSLnKlVhsFpSRbahfwyv5sSQGhDYHRsARnrHiA49
          UV5Efro2I/weI1ZiPeWiGXB5JJ84+5GjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQg46nVDHpFM960dC9s57+AHch3lbEnP3CBsAhjSq0pLkYwCgYIKoZIzj0E
          AwIDSAAwRQIgP1GDEKU9Wfs22dBxQiwpqB3P8TlgLajqvKI1reQuzAoCIQC8G+Dp
          VhO8BM+BxUwTT44ZB+eiokSwflJ+fFKnNWEEDQ==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUDCCAfegAwIBAgIQRgVvzvV7c25Rkf+D53S2DDAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yNDExMTUwOTA4MDBaFw0zNDExMTMwOTA4MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          HVXFfO+Aeur2Jk4eHbjzu06aa1G/LhyRAt5WUsTLRRNWlImc/wbajUHOZr8t8k1z
          w1GBifSg2Y/5ZDyjTfwgUqNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBZ
          rnNHC1LPNmp4A8AcFJ0ztVVeHcvo04r1iFdKnprGRTAKBggqhkjOPQQDAgNHADBE
          AiAzHTczJrs0GUCFzvSfmsJPS3oMMitRowpnu5U3peWPowIgdtjw2y9VjTYyAJUj
          fXDHF5DDGMmHi1L18XGC0az7FSI=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
